# Generated by Django 4.1.7 on 2023-03-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_api', '0004_publisher_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='buyer',
        ),
        migrations.AddField(
            model_name='book',
            name='buyers',
            field=models.ManyToManyField(to='magazine_api.buyer'),
        ),
    ]
