# Generated by Django 4.1.7 on 2023-04-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_api', '0007_alter_book_number_of_pages_alter_publisher_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Magazine',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='book',
            new_name='magazine',
        ),
    ]
